### ISSUE TITLE
Does default Max Samples value (128) match default value in other plugins?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-maya#221]

**Comment by Mango-3** [comment]
The 128 was a compromise value. It arose because Esteban had reused the `Max Samples` field for uniform sampling also for the adaptive tile sampler settings when he implemented the UI controls to have less clutter. 
For uniform sampling one wants a quick scene render feedback, means lower max samples (32) and for adaptive higher ones (256). So 128 was a compromise in-between. 

I made a fix which adjusts the default samples according to sampler type but still uses the same control. 
In Blender and Max we have separate Max Samples controls for uniform and adaptive.

**Comment by dictoon** [comment]
Thanks for the details.

Could we introduce separate controls?

**Comment by Mango-3** [comment]
-> I made a fix which adjusts the default samples according to sampler type but still uses the same control. (Commit a7431754ffdb558294a9802d05fa2476911aa925)

Uniform Sampling (Max Samples 32):
![uniform](https://user-images.githubusercontent.com/22252558/68022990-9ec91c80-fcae-11e9-96d4-61241ad83560.PNG)

Adaptive Sampling (Max Samples 256):
![adaptive](https://user-images.githubusercontent.com/22252558/68023058-d768f600-fcae-11e9-8e7c-801a625544c2.PNG)
